bumps:
  - # The path of the file relative to where uplift is executed
    file: version.json

    # A JSON path matcher should be used when bumping the file. Multiple path
    # matches are supported. Each will be carried out in the order they are
    # defined here. All matches must succeed for the file to be bumped.
    # JSON path syntax is based on https://github.com/tidwall/sjson
    #
    # Defaults to no matchers
    json:
      - # A JSON path that will be used for matching the version that
        # will be replaced within the file
        path: "version"

        # If the matched version in the file should be replaced with a semantic version.
        # This will strip any 'v' prefix if needed
        #
        # Defaults to false
        semver: true
